services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $fontAwesomeConfig: '%font_awesome_config%'

    ContaoThemesNet\FontAwesomeInserttagBundle\:
        resource: ../src/
